# [[ Aliases ]]

alias uva='uv add'
alias uvi='uv init'
alias uvl='uv lock'
alias uvp='uv pip'
alias uvpf='uv pip freeze'
alias uvpi='uv pip install'
alias uvpl='uv pip list'
alias uvps='uv pip show'
alias uvpu='uv pip uninstall'
alias uvpy='uv python'
alias uvpyi='uv python install'
alias uvpyl='uv python list'
alias uvr='uv run'
alias uvrp='uv run python'
alias uvrm='uv remove'
alias uvs='uv sync'
alias uvt='uv tool'
alias uvti='uv tool install'
alias uvtl='uv tool list'
alias uvtr='uv tool run'
alias uvtui='uv tool uninstall'
alias uvtup='uv tool upgrade'
alias uvv='uv venv'
