[tool.black]
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
force-exclude = '''
/(
    notebooks
)/
'''
include = '\.pyi?$'
line-length = 100
target-version = [
  'py310',
  'py311',
  'py39'
]
