repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files # Prevent giant files from being committed
      - id: check-ast # Check whether the files parse as valid python
      - id: check-json # Check json files for parseable syntax
        exclude: /models/
      - id: check-merge-conflict # Check for files that contain merge conflict strings
      - id: check-toml # Checks toml files for parseable syntax
      - id: check-yaml # Check yaml files for parseable syntax
      - id: debug-statements # Check for debugger imports and `breakpoint()` calls in python
      - id: detect-private-key # Detect the presence of private keys
      - id: end-of-file-fixer # Ensures that files end with a newline
      - id: name-tests-test # Verify that test files are named correctly

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.2
    hooks:
      - id: prettier

  - repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
      - id: black

  # When adding certain files in sub-modules of projects/pypa/, for an unknown reason, isort's hook
  # stopped detecting the configuration file automatically, so we have to specify it.
  - repo: https://github.com/PyCQA/isort
    rev: 5.9.1
    hooks:
      - id: isort
        args: ["--settings-path", "pyproject.toml"]

  - repo: https://gitlab.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        exclude: /tests/

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        exclude: /tests/
