# This file defines all the hooks run by pre-commit.

repos:
  # Base pre-commit hook repository, for simple checks & fixes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files # Prevent giant files from being committed
      - id: check-json # Check JSON files for parseable syntax
      - id: check-merge-conflict # Check for files that contain merge conflict strings
      - id: check-toml # Checks TOML files for parseable syntax
      - id: check-yaml # Check YAML files for parseable syntax
      - id: detect-private-key # Detect the presence of private keys
      - id: end-of-file-fixer # Ensures that files end with a newline
        exclude: .config/pycharm/keymaps/

  # Prettier is a formatting tool for many non-Python files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.6
    hooks:
      - id: prettier

  # TOML-sort is used to re-organize alphabetically TOML files (such as pyproject.toml)
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.22.4
    hooks:
      - id: toml-sort
        args: ["--all", "--in-place"]
