extend-ignore = [
  "S311" # Standard pseudo-random generators are not suitable for cryptographic purposes
]
extend-select = [
  "I", # isort
  "S" # flake8-bandit
]
line-length = 100
target-version = "py311"

[extend-per-file-ignores]
"__init__.py" = [
  "F401" # {name} imported but unused
]
