line-length = 100
target-version = "py312"

[lint]
extend-ignore = [
  "S311", # Standard pseudo-random generators are not suitable for cryptographic purposes
]
extend-select = [
  "E", # pycodestyle
  "F", # pyflakes
  "I", # isort
  "S", # flake8-bandit
]

[lint.extend-per-file-ignores]
"tests/**/*_test.py" = ["S101"] # Use of assert detected
