# To add this configuration in a `pyproject.toml` file instead of `.ruff.toml`, move the general
# Ruff configuration (e.g. `line-length`) under the section `[tool.ruff]`, and prefix the
# sub-sections by `tool.ruff.` (e.g. `[tool.ruff.lint]`)

line-length = 100
target-version = "py312"

[lint]
extend-select = [ # Extend default lint rules
  "E", # pycodestyle
  "I", # isort
]

[lint.extend-per-file-ignores] # Extend default set of rules to ignore per-file 
"__init__.py" = ["F401"] # Module imported but unused
