extends: default

rules:
  # Make rules compatible with popular YAML formatters
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable
  document-start: disable
  line-length:
    max: 100
  truthy:
    check-keys: false # Trigger irrelevant warning in GitHub workflows' "on" key
