alias tm='tmux'
alias tma='tmux attach'  # Attach to last session
alias tmas='tmux attach -t'  # Attach to session with name
alias tmd='tmux detach'
alias tmks='tmux kill-session -t'  # Kill session with name
alias tmK='tmux kill-server'
alias tml='tmux ls'
alias tmr='tmux rename'
alias tms='tmux new -s'  # New session with name
