alias tm='tmux'
alias tma='tmux attach'
alias tmd='tmux detach'
alias tmk='tmux kill-server'
alias tmls='tmux ls'
alias tmn='tmux new'
alias tmrn='tmux rename'
alias tmso='tmux source-file ~/.config/tmux/tmux.conf'
