alias tm='tmux'
alias tma='tmux attach'
alias tmd='tmux detach'
alias tmk='tmux kill-server'
alias tml='tmux ls'
alias tmn='tmux new'
alias tmr='tmux rename'
alias tms='tmux source-file ~/.config/tmux/tmux.conf'
