# [[ Aliases ]]

alias dkb='docker build'
alias dkc='docker container'
alias dkcl='docker container ls'
alias dkcp='docker container prune'
alias dkcr='docker container rm'
alias dke='docker exec'
alias dki='docker image'
alias dkil='docker image ls'
alias dkip='docker image prune'
alias dkir='docker image rm'
alias dkp='docker ps'
alias dkpl='docker pull'
alias dkps='docker push'
alias dkr='docker run'
alias dkrm='docker rm'
alias dks='docker start'
alias dkst='docker stop'
alias dksy='docker system'
alias dksyd='docker system df'
alias dksyp='docker system prune'
alias dkv='docker volume'
alias dkvl='docker volume ls'
alias dkvp='docker volume prune'
alias dkvr='docker volume rm'

# Use `docker compose` instead of `docker-compose` will make completions available
alias dcb='docker compose build'
alias dce='docker compose exec'
alias dcd='docker compose down'
alias dcl='docker compose ls'
alias dcp='docker compose ps'
alias dcpl='docker compose pull'
alias dcps='docker compose push'
alias dcr='docker compose run'
alias dcrm='docker compose rm'
alias dcs='docker compose start'
alias dcst='docker compose stop'
alias dcu='docker compose up'
