config-version = 2

start-at-login = true

accordion-padding = 150
persistent-workspaces = ["1", "2", "3", "4"] # A 5th workspace is added when using a second display

after-startup-command = [
  'layout --workspace 1 --root accordion',
  'layout --workspace 4 --root accordion',
]

[gaps]
inner.horizontal = 20
inner.vertical = 20
outer.bottom = 30
outer.left = 40
outer.right = 40
outer.top = 30

[mode.main.binding]

cmd-alt-ctrl-h = 'focus left'
cmd-alt-ctrl-j = 'focus down'
cmd-alt-ctrl-k = 'focus up'
cmd-alt-ctrl-l = 'focus right'
cmd-alt-ctrl-shift-h = 'move left'
cmd-alt-ctrl-shift-j = 'move down'
cmd-alt-ctrl-shift-k = 'move up'
cmd-alt-ctrl-shift-l = 'move right'

# `list-workspaces --empty no` excludes the focused workspace if it's empty, which leads to a jump
# to an unexpected workspace, hence the double `list-workspaces` call and the numeric merge with `sort -n -u`
cmd-alt-ctrl-n = 'exec-and-forget { aerospace list-workspaces --monitor focused --empty no; aerospace list-workspaces --focused; } | sort -n -u | aerospace workspace --stdin next'
cmd-alt-ctrl-p = 'exec-and-forget { aerospace list-workspaces --monitor focused --empty no; aerospace list-workspaces --focused; } | sort -n -u | aerospace workspace --stdin prev'
cmd-alt-ctrl-shift-n = ['move-node-to-workspace next', 'workspace next']
cmd-alt-ctrl-shift-p = ['move-node-to-workspace prev', 'workspace prev']

cmd-alt-ctrl-1 = 'workspace 1'
cmd-alt-ctrl-2 = 'workspace 2'
cmd-alt-ctrl-3 = 'workspace 3'
cmd-alt-ctrl-4 = 'workspace 4'
cmd-alt-ctrl-5 = 'workspace 5'
cmd-alt-ctrl-6 = 'workspace 6'
cmd-alt-ctrl-7 = 'workspace 7'
cmd-alt-ctrl-8 = 'workspace 8'
cmd-alt-ctrl-9 = 'workspace 9'
cmd-alt-ctrl-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
cmd-alt-ctrl-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
cmd-alt-ctrl-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
cmd-alt-ctrl-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
cmd-alt-ctrl-shift-5 = ['move-node-to-workspace 5', 'workspace 5']
cmd-alt-ctrl-shift-6 = ['move-node-to-workspace 6', 'workspace 6']
cmd-alt-ctrl-shift-7 = ['move-node-to-workspace 7', 'workspace 7']
cmd-alt-ctrl-shift-8 = ['move-node-to-workspace 8', 'workspace 8']
cmd-alt-ctrl-shift-9 = ['move-node-to-workspace 9', 'workspace 9']

cmd-alt-ctrl-b = 'workspace-back-and-forth'

cmd-alt-ctrl-equal = 'resize smart +50'
cmd-alt-ctrl-minus = 'resize smart -50'

cmd-alt-ctrl-space = 'mode service'

[mode.service.binding]
f = ['layout floating tiling', 'mode main'] # Toggle floating
t = ['flatten-workspace-tree', 'mode main'] # Reset tiling tree
z = ['fullscreen', 'mode main'] # Toggle zoom

h = ['join-with left', "mode main"]
j = ['join-with down', "mode main"]
k = ['join-with up', "mode main"]
l = ['join-with right', "mode main"]

m = ['layout tiles accordion', 'mode main'] # Change layout mode
o = ['layout horizontal vertical', 'mode main'] # Change layout orientation

d = ['enable off'] # Disable 
r = ['reload-config', 'mode main'] # Reload config

esc = ['mode main']

[[on-window-detected]]
if.app-name-regex-substring = 'Archive Utility|Finder|Preview|System Settings|TextEdit'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'Slack|Spotify'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-name-regex-substring = 'Zen|Firefox'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-name-regex-substring = 'WezTerm'
run = 'move-node-to-workspace 3'

[[on-window-detected]] # Last section: all the rest
if = 'true'
run = 'move-node-to-workspace 4'
