alias pif='pip freeze'                     # [F]reeze: output installed packages in requirements format
alias pifr='pip freeze > requirements.txt' # [F]reeze [R]equirements.txt: output installed packages in a requirements.txt file
alias pii='pip install'                    # [I]nstall: install a package
alias piie='pip isntall -e'                # [I]nstall [E]ditable: install a local package in editable mode
alias piir='pip install -r'                # [I]nstall [R]equirements: install packages from a requirements file
alias pil='pip list'                       # [L]ist: list installed packages
alias pis='pip show'                       # [S]how: show installed package information
alias piup='pip install --upgrade'         # [U][P]grade: upgrade a package
alias piui='pip uninstall'                 # [U]n[I]nstall: uninstall a package
