#!/bin/bash

ITEM_DIR="$CONFIG_DIR/items"
PLUGIN_DIR="$CONFIG_DIR/plugins"

FONT="JetBrainsMono Nerd Font:Bold"

source "$CONFIG_DIR/colors.sh"

bar=(
	color="$TRANSPARENT"
	position=right
	height=50
	margin=5
	y_offset=5
)
default=(
	label.font="$FONT:13.0"
	icon.font="$FONT:13.0"
	padding_left=2
	padding_right=2
)
sketchybar --bar "${bar[@]}" --default "${default[@]}"

# Left (top to bottom)
source "$ITEM_DIR/spaces.sh"

# Right (bottom to top)
source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/slack.sh"

sketchybar --update # Finalize setup
